In [3]:
import os
import sys

import numpy as np
import pandas as pd
from subprocess import call
from sklearn.metrics import mean_squared_error

from numpy.linalg import solve

import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set()

# library test

In [7]:
!python -V

Python 3.6.3 :: Anaconda, Inc.


In [385]:
!python lib/TF.py --train data/ml-1m/user_train.txt --test data/ml-1m/user_test.txt --reg 0.1 --regS 0.1 --lr 0.0001 --lrS 0.0001

[INFO] ----------------- TF -----------------
[INFO] Data: Number of types for each feature = [6040, 3883, 2, 7, 21]
[INFO] Data: Training Size = 900188. Testing Size = 100021
[INFO] Settings: K = [8, 8, 8, 8, 8]. reg = 0.1. regS = 0.1. lr = 0.0001. lrS = 0.0001
^C
Traceback (most recent call last):
  File "lib/TF.py", line 224, in <module>
    core, U = TPTF(X, Xtest, dims, rank, args.reg, args.regS, args.lr, args.lrS, args.maxEpo)
  File "lib/TF.py", line 74, in TPTF
    F_ijk = tensor_ttv(core, Ui_list)
  File "lib/TF.py", line 136, in tensor_ttv
    out_core = dt_core.ttv(tuple(Ui_list), modes)
  File "/home/5124393/scikit-tensor-py3/sktensor/core.py", line 121, in ttv
    dims, vidx = check_multiplication_dims(modes, self.ndim, len(v), vidx=True, without=without)
  File "/home/5124393/scikit-tensor-py3/sktensor/core.py", line 245, in check_multiplication_dims
    if not np.in1d(dims, np.arange(N)).all():
  File "/home/5124393/anaconda3/lib/python3.6/site-packages/numpy/lib/arrayse

In [384]:
!python lib/TF.py --help

usage: TF.py [-h] [--train TRAIN] [--test TEST] [--model MODEL] [--out OUT]
             [--k K] [--reg REG] [--regS REGS] [--lr LR] [--lrS LRS]
             [--maxEpo MAXEPO] [--verbose VERBOSE]

Tensor Factorization

optional arguments:
  -h, --help         show this help message and exit
  --train TRAIN      Training file
  --test TEST        Testing file
  --model MODEL      Directory where the final model will be saved
  --out OUT          File where the final result will be saved
  --k K              Dimension of latent fectors, e.g. '8-8-8'
  --reg REG          Regularization for latent facotrs
  --regS REGS        Regularization for core tensor
  --lr LR            Initial learning rate for latent facotrs
  --lrS LRS          Initial learning rate for core tensor
  --maxEpo MAXEPO    Max training epo
  --verbose VERBOSE  Verbose or not


In [379]:
!python lib/TF.py --train data/test/small_train.txt --test data/test/small_test.txt --reg 0.1 --regS 0.1 --lr 0.001 --lrS 0.001 --model model

[INFO] ----------------- TF -----------------
[INFO] Data: Number of types for each feature = [100, 99, 2, 7, 21]
[INFO] Data: Training Size = 200. Testing Size = 57
[INFO] Settings: K = [8, 8, 8, 8, 8]. reg = 0.1. regS = 0.1. lr = 0.001. lrS = 0.001
[INFO] Iter 1/10. Time: 0.7
[INFO] Training Loss: 5.60 (change -659.55%). Testing RMSE: 3.7757
[INFO] Iter 2/10. Time: 0.7
[INFO] Training Loss: 5.50 (change -1.64%). Testing RMSE: 3.7651
[INFO] Iter 3/10. Time: 0.7
[INFO] Training Loss: 5.42 (change -1.59%). Testing RMSE: 3.7460
[INFO] Iter 4/10. Time: 0.7
[INFO] Training Loss: 5.33 (change -1.51%). Testing RMSE: 3.7029
[INFO] Iter 5/10. Time: 0.7
[INFO] Training Loss: 5.26 (change -1.35%). Testing RMSE: 3.5582
[INFO] Iter 6/10. Time: 0.7
[INFO] Training Loss: 5.20 (change -1.27%). Testing RMSE: 2.9498
[INFO] Iter 7/10. Time: 0.7
[INFO] Training Loss: 5.09 (change -1.97%). Testing RMSE: 2.3119
[INFO] Iter 8/10. Time: 0.7
[INFO] Training Loss: 5.00 (change -1.91%). Testing RMSE: 1.8609
[IN

In [60]:
X = np.loadtxt('data/test/small_train.txt', dtype=float, delimiter=',')
X_test = np.loadtxt('data/test/small_test.txt', dtype=float, delimiter=',')

In [54]:
core = np.load('model/8_0.1_0.1_0.001_0.001_10_core.npy')
U = np.load('model/8_0.1_0.1_0.001_0.001_10_U.npy')
pred = np.load('model/pred.npy')

In [51]:
X

array([[ 59.,   0.,   0.,   5.,   1.,   4.],
       [ 91.,  23.,   1.,   1.,   4.,   2.],
       [ 44.,  10.,   1.,   4.,  16.,   5.],
       ..., 
       [ 91.,  33.,   1.,   1.,   4.,   3.],
       [ 82.,  59.,   1.,   2.,   2.,   5.],
       [ 47.,  23.,   0.,   2.,   4.,   3.]])

In [59]:
X.shape

(200, 6)

In [62]:
X_test

array([[ 91.,  85.,   1.,   1.,   4.,   1.],
       [ 50.,  38.,   1.,   0.,  10.,   4.],
       [ 61.,  84.,   1.,   3.,   3.,   2.],
       [ 91.,  75.,   1.,   1.,   4.,   2.],
       [ 48.,  20.,   0.,   1.,  12.,   3.],
       [ 71.,  16.,   1.,   4.,   0.,   4.],
       [ 61.,  98.,   1.,   3.,   3.,   3.],
       [ 47.,   5.,   0.,   2.,   4.,   4.],
       [ 31.,  31.,   1.,   2.,   0.,   5.],
       [ 94.,   9.,   0.,   4.,   0.,   4.],
       [ 74.,   7.,   1.,   0.,  10.,   5.],
       [ 61.,   6.,   1.,   3.,   3.,   3.],
       [ 34.,   6.,   0.,   4.,   1.,   2.],
       [ 68.,  39.,   1.,   2.,   1.,   5.],
       [ 86.,  20.,   0.,   2.,  14.,   1.],
       [ 57.,  93.,   0.,   2.,   2.,   2.],
       [ 57.,  28.,   0.,   2.,   2.,   5.],
       [ 66.,  35.,   1.,   5.,   5.,   5.],
       [ 68.,  57.,   1.,   2.,   1.,   4.],
       [ 61.,  35.,   1.,   3.,   3.,   3.],
       [ 47.,  35.,   0.,   2.,   4.,   3.],
       [ 57.,  20.,   0.,   2.,   2.,   4.],
       [ 5

In [61]:
X_test.shape

(57, 6)

In [63]:
X_test.T[5]

array([ 1.,  4.,  2.,  2.,  3.,  4.,  3.,  4.,  5.,  4.,  5.,  3.,  2.,
        5.,  1.,  2.,  5.,  5.,  4.,  3.,  3.,  4.,  4.,  3.,  5.,  5.,
        4.,  5.,  3.,  5.,  2.,  5.,  5.,  3.,  4.,  3.,  4.,  1.,  4.,
        3.,  3.,  3.,  3.,  4.,  4.,  4.,  3.,  4.,  3.,  3.,  5.,  5.,
        3.,  4.,  5.,  4.,  5.])

In [55]:
pred

array([ 2.33777904,  2.02696961,  2.16947334,  2.18639081,  3.70185344,
        4.39216015,  3.55975776,  3.38314889,  2.743418  ,  4.24352339,
        2.12984109,  2.8131916 ,  2.83659153,  4.86570043,  0.43582863,
        2.4963158 ,  3.82049556,  0.50975272,  4.07316279,  3.6473105 ,
        2.74748467,  4.3741594 ,  2.9172552 ,  3.68828958,  4.03411823,
        4.05301415,  0.91725884,  5.00844812,  1.78234021,  0.95299233,
        2.11066424,  5.73760899,  4.83981144,  3.55484116,  3.68596962,
        1.55953711,  2.85461574,  4.18819273,  3.02581286,  2.13295425,
        3.61557562,  1.40446623,  2.01233423,  4.14924381,  1.60801235,
        1.3829351 ,  3.07503682,  3.25492081,  2.23555799,  2.33654767,
        1.30351026,  3.08798556,  0.99815251,  4.0844401 ,  3.6312516 ,
        3.84613671,  7.61266274])

In [56]:
len(pred)

57

In [94]:
X_test[0]

array([ 91.,  85.,   1.,   1.,   4.,   1.])

In [103]:
U.shape

(5,)

In [107]:
U0 = U[0][91]
U0

array([ 0.12360956,  0.09643034,  0.10695808,  0.0580915 ,  0.06128392,
        0.04122145,  0.11231868,  0.10586959])

In [109]:
U1 = U[1][85]
U1

array([ 0.10513069,  0.05847092,  0.08913046,  0.07529403,  0.1467173 ,
        0.07188967,  0.11083931,  0.06362633])

In [110]:
U2 = U[2][1]
U2

array([ 0.32178458,  0.36415049,  0.41291774,  0.39071077,  0.36792984,
        0.41311118,  0.4285397 ,  0.37567135])

In [111]:
U3 = U[3][1]
U3

array([ 0.29703738,  0.30535875,  0.23706344,  0.25744111,  0.19834795,
        0.27630989,  0.2567346 ,  0.22103808])

In [112]:
U4 = U[4][4]
U4

array([ 0.26245665,  0.19427385,  0.23438455,  0.252674  ,  0.19719317,
        0.18496519,  0.20312887,  0.24918685])

In [97]:
core.shape

(8, 8, 8, 8, 8)

In [104]:
def tensor_ttv(core, Ui_list, remove_k=None):
	'''
	Tensor times vector product (use sktensor library)
	-----------
	core = core tensor
	Ui_list = list of U_i to be multiplied
	remove_k = do not multiply in k-th mode
	return a scalar or np.array
	'''
	dt_core = sktensor.dtensor(core)
	assert( dt_core.ndim == len(Ui_list) ), "tensor_ttv: core and U must be tha same dimension."
	#
	modes = list(range(len(Ui_list)))
	if remove_k is not None:
		modes.remove(remove_k)
	#
	out_core = dt_core.ttv(tuple(Ui_list), modes)
	#
	if len(out_core) == 1: # out_core is a scaler
		return( out_core[0] )
	else:
		return( np.array(out_core) )

In [113]:
tensor_ttv(core, [U0, U1, U2, U3, U4])

2.3377790422150611

In [31]:
import logging
from sktensor import dtensor, cp_als

logging.basicConfig(level=logging.DEBUG)

In [22]:
T = dtensor(X)

In [90]:
X

array([[ 59.,   0.,   0.,   5.,   1.,   4.],
       [ 91.,  23.,   1.,   1.,   4.,   2.],
       [ 44.,  10.,   1.,   4.,  16.,   5.],
       ..., 
       [ 91.,  33.,   1.,   1.,   4.,   3.],
       [ 82.,  59.,   1.,   2.,   2.,   5.],
       [ 47.,  23.,   0.,   2.,   4.,   3.]])

In [91]:
X.shape

(200, 6)

In [23]:
T

dtensor([[ 59.,   0.,   0.,   5.,   1.,   4.],
         [ 91.,  23.,   1.,   1.,   4.,   2.],
         [ 44.,  10.,   1.,   4.,  16.,   5.],
         ..., 
         [ 91.,  33.,   1.,   1.,   4.,   3.],
         [ 82.,  59.,   1.,   2.,   2.,   5.],
         [ 47.,  23.,   0.,   2.,   4.,   3.]])

In [32]:
P, fit, itr = cp_als(T, 3, init='random')

DEBUG:CP:[  0] fit: 0.97667 | delta: 9.8e-01
DEBUG:CP:[  1] fit: 0.99903 | delta: 2.2e-02
DEBUG:CP:[  2] fit: 0.99906 | delta: 2.7e-05
DEBUG:CP:[  3] fit: 0.99906 | delta: 2.2e-07


In [28]:
fit

dtensor([ 0.99906124])

In [29]:
P

In [30]:
P.rank

3

In [33]:
P.shape

(200, 6)

In [34]:
P.ndim

2

In [36]:
P.toarray()

unfolded_dtensor([[  5.91388899e+01,   2.99931709e-02,   3.55887244e-01,
                     1.78930409e+00,   1.13076227e+00,   3.10997386e+00],
                  [  9.07878695e+01,   2.29623378e+01,   5.60372902e-01,
                     2.98060071e+00,   3.85394240e+00,   5.00760989e+00],
                  [  4.41814100e+01,   1.00331059e+01,   2.57650576e-01,
                     1.90014314e+00,   1.61278074e+01,   2.78835777e+00],
                  ..., 
                  [  9.08333715e+01,   3.29690106e+01,   5.67675655e-01,
                     3.05499746e+00,   3.87582925e+00,   5.08901721e+00],
                  [  8.19868700e+01,   5.89953621e+01,   5.34509817e-01,
                     2.91988618e+00,   1.97467658e+00,   4.78416737e+00],
                  [  4.70213323e+01,   2.30041502e+01,   2.96038517e-01,
                     1.68901325e+00,   4.01773649e+00,   2.73183557e+00]])

In [42]:
P.toarray()[0]

unfolded_dtensor([  5.91388899e+01,   2.99931709e-02,   3.55887244e-01,
                    1.78930409e+00,   1.13076227e+00,   3.10997386e+00])

In [43]:
X[0]

array([ 59.,   0.,   0.,   5.,   1.,   4.])

# Train Data

In [85]:
PROJECT_PATH = '/home/5124393/ML_Tips/08_Recommend/'
DATA_FILE_PATH = os.path.join(PROJECT_PATH, 'data')

In [171]:
df_time_context = pd.DataFrame()
for category_id in range(4):
    df = pd.read_csv(os.path.join(DATA_FILE_PATH, 'train',
                                    'category_id_{}_recommend_table_week_201904.csv'.format(str(category_id))))
    df = df[['cuid', 'genre_id', 'time', 'poi_type', 'score']]
    df_time_context = pd.concat([df_time_context, df])

In [121]:
df_time_context.head()

cuid  genre_id  time  poi_type  score
0  04GG05555QJN55QTP4O05TPL         0     0        13     77
1  04GG05555QJN55QTP4O05TPL         0     1        13     32
2  04GG05555QJN55QTP4O05TPL         0     2        13     20
3  04GG05555QJN55QTP4O05TPL         0     3        13     17
4  04GG05555QJN55QTP4O05TPL         0     4        13     18

In [122]:
df_time_context.shape

(78418, 5)

## cuid to index

In [172]:
#indexing
unique_cuids = set(df_time_context.cuid.unique())
u2i = {u:i for i, u in enumerate(unique_cuids)}
i2u = {i:u for i, u in enumerate(unique_cuids)}

In [173]:
df_time_context['cuid_index'] = df_time_context['cuid'].map(lambda x:u2i[x])

## get train

In [174]:
train = df_time_context[['cuid_index', 'genre_id', 'time', 'poi_type', 'score']]

In [176]:
train.head()

cuid_index  genre_id  time  poi_type  score
0        2208         0     0        13     77
1        2208         0     1        13     32
2        2208         0     2        13     20
3        2208         0     3        13     17
4        2208         0     4        13     18

In [177]:
print(len(df_time_context['cuid_index'].unique()))
print(len(df_time_context['genre_id'].unique()))
print(len(df_time_context['time'].unique()))
print(len(df_time_context['poi_type'].unique()))

7082
4
24
24


## get test

In [178]:
unique_cuids = set(df_time_context.cuid_index.unique())
unique_genres = set(df_time_context.genre_id.unique())
unique_contexts = set(df_time_context.poi_type.unique())

num_cuid = len(unique_cuids)
num_genre = len(unique_genres)
num_context = len(unique_contexts)
num_time = 24

In [179]:
num_cuid, num_genre, num_context, num_time

(7082, 4, 24, 24)

In [180]:
from sklearn.utils.extmath import cartesian

df_combination = pd.DataFrame(cartesian((list(unique_cuids), list(unique_genres), list(range(24)), list(unique_contexts))))

In [182]:
df_combination.rename(columns={0: 'cuid_index', 1: 'genre_id', 2: 'time', 3: 'poi_type'}, inplace=True)

In [183]:
df_combination.head()

cuid_index  genre_id  time  poi_type
0           0         0     0         2
1           0         0     0       133
2           0         0     0       134
3           0         0     0         8
4           0         0     0        13

In [184]:
df_combination.shape

(16316928, 4)

In [185]:
df_combination['genre_id'] = df_combination['genre_id'].astype(int)
df_combination['time'] = df_combination['time'].astype(int)
df_combination['poi_type'] = df_combination['poi_type'].astype(int)

In [186]:
df_merge = pd.merge(df_combination, df_time_context, on=['cuid_index', 'genre_id', 'time', 'poi_type'], how='left')

In [187]:
df_nan = df_merge[df_merge['score'].isnull()]
test = df_nan[['cuid_index', 'genre_id', 'time', 'poi_type']]

In [188]:
train.head()

cuid_index  genre_id  time  poi_type  score
0        2208         0     0        13     77
1        2208         0     1        13     32
2        2208         0     2        13     20
3        2208         0     3        13     17
4        2208         0     4        13     18

In [263]:
train.shape

(78418, 5)

In [190]:
test.head()

cuid_index  genre_id  time  poi_type
0           0         0     0         2
1           0         0     0       133
2           0         0     0       134
3           0         0     0         8
4           0         0     0        13

In [191]:
test.shape

(16238510, 4)

## get input array

In [194]:
train_matrix = train.as_matrix()

In [195]:
train_matrix

array([[2208,    0,    0,   13,   77],
       [2208,    0,    1,   13,   32],
       [2208,    0,    2,   13,   20],
       ..., 
       [ 973,    3,   20,   13,    5],
       [ 973,    3,   21,  109,    4],
       [5716,    3,   21,   13,    2]])

In [196]:
test_matrix = test.as_matrix()

In [197]:
test_matrix

array([[   0,    0,    0,    2],
       [   0,    0,    0,  133],
       [   0,    0,    0,  134],
       ..., 
       [7081,    3,   23,  104],
       [7081,    3,   23,  109],
       [7081,    3,   23,  110]])

## prepare

In [212]:
def get_XY_dims(X, isTest=False):
    if isTest is False:
        ndims = X.shape[1]-1
        Y = X.T[ndims]
        X = np.delete(X, ndims, 1).astype(int)
    else:
        ndims = X.shape[1]
        Y = [0] * X.shape[0]
        Y = np.array(Y)
        
    dims = [X.T[i].max()+1 for i in range(ndims)]
    return [X, Y], dims

In [224]:
X, trn_dims = get_XY_dims(train_matrix)
Xtest, tst_dims = get_XY_dims(test_matrix, isTest=True)

In [225]:
X

[array([[2208,    0,    0,   13],
        [2208,    0,    1,   13],
        [2208,    0,    2,   13],
        ..., 
        [ 973,    3,   20,   13],
        [ 973,    3,   21,  109],
        [5716,    3,   21,   13]]), array([77, 32, 20, ...,  5,  4,  2])]

In [226]:
Xtest

[array([[   0,    0,    0,    2],
        [   0,    0,    0,  133],
        [   0,    0,    0,  134],
        ..., 
        [7081,    3,   23,  104],
        [7081,    3,   23,  109],
        [7081,    3,   23,  110]]), array([0, 0, 0, ..., 0, 0, 0])]

In [216]:
def integrate_dims(dim1, dim2):
	'''
	To avoid training and testing data with different dimensions.
	'''
	assert( len(dim1) == len(dim2) ), "Training and testing data must have the same number of features."
	dims = [max(dim1[i], dim2[i]) for i in range(len(dim1))]
	return(dims)

In [217]:
def string2list(k, ndims):
	k_list = k.split('-')
	last_k = int(k_list[len(k_list)-1])
	rank = [int(k_list[x]) if (x < len(k_list)) else (last_k) for x in range(ndims)]
	return rank

In [219]:
dims = integrate_dims(tst_dims, trn_dims)

k = '8'
rank = string2list(k, len(dims))

## train

In [325]:
import time
import logging
import time
from functools import reduce

from statistics import mean

In [228]:
def init_factors(rank, dims):
	'''
	Initialize tensor and matrix with small random values
	'''
	assert(len(rank) == len(dims)), "Rank must be the same length as number of features."
	Core = np.random.rand(multiply_list(rank)).reshape(rank) # / multiply_list(rank)
	U = [np.random.rand(dims[i], rank[i])/rank[i] for i in range(len(dims))]
	return Core, U

In [230]:
def tensor_ttv(core, Ui_list, remove_k=None):
	'''
	Tensor times vector product (use sktensor library)
	-----------
	core = core tensor
	Ui_list = list of U_i to be multiplied
	remove_k = do not multiply in k-th mode
	return a scalar or np.array
	'''
	dt_core = sktensor.dtensor(core)
	assert( dt_core.ndim == len(Ui_list) ), "tensor_ttv: core and U must be tha same dimension."
	#
	modes = list(range(len(Ui_list)))
	if remove_k is not None:
		modes.remove(remove_k)
	#
	out_core = dt_core.ttv(tuple(Ui_list), modes)
	#
	if len(out_core) == 1: # out_core is a scaler
		return( out_core[0] )
	else:
		return( np.array(out_core) )

def training_loss(loss, core, U, reg, reg_S):
	U_l2 = [np.linalg.norm(Ui.flat) for Ui in U]
	core_l1 = np.linalg.norm(core.flat, ord = 1)
	core_l2 = np.linalg.norm(core.flat)
	return( loss / core_l1 + reg / 2 * sum(U_l2) + reg_S / 2 * core_l2 )

def testing_loss(X, Y, core, U, reg, reg_S):
	'''
	X: orign value (np array or list)
	Y: predicted value (np array or list)
	return: objective loss
	'''
	assert( len(X)==len(Y) ), "Loss: Two different size arrays."
	U_l2 = [np.linalg.norm(Ui.flat) for Ui in U]
	core_l1 = np.linalg.norm(core.flat, ord = 1)
	core_l2 = np.linalg.norm(core.flat)
	return( sum( pow(X-Y, 2) ) / core_l1 + reg / 2 * sum(U_l2) + reg_S / 2 * core_l2 )

In [231]:
def multiply_list(lst):
	product = 1
	for itm in lst:
		product *= itm
	return(product)

def integrate_dims(dim1, dim2):
	'''
	To avoid training and testing data with different dimensions.
	'''
	assert( len(dim1) == len(dim2) ), "Training and testing data must have the same number of features."
	dims = [max(dim1[i], dim2[i]) for i in range(len(dim1))]
	return(dims)

In [390]:
def TPTF(X, Xtest, dims, rank, reg, reg_S, lr, lrS, max_iter, tol=0):
    '''
    Tucker decomposition with ALS and SGD
    -----------------------------------
    X, Xtest = n-dimension tensor presented in [2D matrix, 1D array]
    dims, rank = used to init core and U
    rank = # of factors for each feature
    '''
    assert(len(X) == 2 and len(Xtest) == 2), "TPTF: no rating values."
    assert(X[0].ndim == 2 and Xtest[0].ndim == 2), "TPTF: X must be a 2D matrix."
    assert(X[0].shape[0] == len(X[1]) and Xtest[0].shape[0] == len(Xtest[1])), "TPTF: rating and index must have the same length."
    
    logger = logging.getLogger()
    
    t = int( pow( 1/lr, 2) )
    t_S = int( pow( 1/lrS, 2) )
    
    trn_x = X[0] # index of training data
    tst_x = Xtest[0] # index of testing data
    
    trn_y = X[1] # rating values of training data
    tst_y = Xtest[1] # rating values of testing data
    
    ninstance = trn_x.shape[0]
    ndims = trn_x.shape[1]
    print('ninstance: {}, ndims: {}'.format(ninstance, ndims))
    
    iter_count = 0
    pre_loss = -1
    
    # initialze core and U
    core, U = init_factors(rank, dims)
    
    tic = time.time()
    while iter_count < max_iter:
        iter_count += 1
        trn_loss = 0
        # Training 
        for i in np.random.permutation(ninstance): # pick on instance in X randomly
            # Compute learn rate
            lr = 1 / np.sqrt(t)
            lrS = 1 / np.sqrt(t_S)
            t += 1
            t_S += 1
            
            ind = trn_x[i]
            val = trn_y[i]
    
            # Compute F_ijk and f - y
            Ui_list = [U[k][ind[k]] for k in range(ndims)]
            F_ijk = tensor_ttv(core, Ui_list)
            e_ijk = F_ijk - val
            trn_loss += pow(e_ijk, 2)
            
#             print('e_ijk:{}'.format(e_ijk))
            # Update U
            for k in range(ndims):
                step = lr * reg * U[k][ind[k]].copy()
#                 print(Ui_list[0])
                step += lr * e_ijk * tensor_ttv(core, Ui_list, k)
#                 print(tensor_ttv(core, Ui_list, k))
#                 print(mean(step))
#                 if mean(step) < 0.001:
                U[k][ind[k]] -= step
                Ui_list = [U[k][ind[k]] for k in range(ndims)]
    
            # Update core tensor
            step_S = lrS * reg_S * core.copy()
            step_S += lrS * e_ijk * reduce(np.multiply.outer, Ui_list)
            core -= step_S
#             print(mean(step))
#             print(core[0][0][0][0])
            
#             print(ind)
#             print(val)
            
    
        # Training Loss
        trn_loss = training_loss(trn_loss, core, U, reg, reg_S)
        change_rate = (trn_loss - pre_loss) / pre_loss * 100
        
        ### Testing Loss
        #tst_pred_y = pred(Xtest[0], core, U)
        #test_rmse = RMSE(tst_y, tst_pred_y)
        ## tst_loss = testing_loss(tst_y, tst_pred_y, core, U, reg, reg_S)
        
        toc = time.time()
        logger.info('Iter {}/{}. Time: {:.1f}'.format(iter_count, max_iter, toc - tic))
        #logger.info('Training Loss: {:.2f} (change {:.2f}%). Testing RMSE: {:.4f}'.format(trn_loss, change_rate, test_rmse))
        logger.info('Training Loss: {:.2f} (change {:.2f}%)'.format(trn_loss, change_rate))
        tic = time.time()
    
        ''' Early Stopping
        if change_rate < tol and pre_loss > 0:
            print("[TF] Early Stoping due to insufficient change in training loss!")
            iter_count = max_iter
            break
        '''
        
        if np.isnan(trn_loss): # numpy overflow, need to use less learning rate
            logger.info('TF: Overflow')
            iter_count = max_iter
            break
    
        pre_loss = trn_loss
        
    return core, U

In [387]:
reg = 0.1
regS = 0.1
lr = 0.0001
lrS = 0.0001

maxEpo = 10

In [306]:
trn_x = X[0]
ind = [5261, 0, 11, 13]
val = 3
ndims = trn_x.shape[1]
core, U = init_factors(rank, dims)

Ui_list = [U[k][ind[k]] for k in range(ndims)]
F_ijk = tensor_ttv(core, Ui_list)
e_ijk = F_ijk - val
trn_loss = pow(e_ijk, 2)

# Update U
for k in range(ndims):
    step = lr * reg * U[k][ind[k]].copy()
    step += lr * e_ijk * tensor_ttv(core, Ui_list, k)
    print(step)
    U[k][ind[k]] -= step
    Ui_list = [U[k][ind[k]] for k in range(ndims)]
    
# Update core tensor
step_S = lrS * regS * core.copy()
step_S += lrS * e_ijk * reduce(np.multiply.outer, Ui_list)
core -= step_S

[-0.00021049 -0.00019148 -0.00019711 -0.00020162 -0.0002131  -0.00020457
 -0.00020821 -0.00019797]
[-0.00023035 -0.0002327  -0.00025599 -0.00023712 -0.00024564 -0.0002414
 -0.00026767 -0.00024597]
[-0.00024263 -0.00023649 -0.00024249 -0.00022705 -0.00024544 -0.00022545
 -0.00025024 -0.00023875]
[-0.00026922 -0.00027216 -0.00027355 -0.00031077 -0.00024391 -0.00026914
 -0.0002628  -0.00026511]


In [355]:
Ui_list

[array([ 0.12310924,  0.08482861,  0.09228387,  0.10901772,  0.03538306,
         0.12166675,  0.0403222 ,  0.02236654]),
 array([ 0.12093759,  0.06082365,  0.00230832,  0.10587609,  0.07690831,
         0.00835971,  0.0997314 ,  0.05684544]),
 array([ 0.10073455,  0.09948272,  0.02674889,  0.07725074,  0.08942248,
         0.1194414 ,  0.03253643,  0.00257674]),
 array([ 0.08459246,  0.01291622,  0.05692677,  0.04551438,  0.09717301,
         0.02756691,  0.04519485,  0.12169245])]

In [350]:
step[0]

-0.0002692236489912174

In [349]:
core[0][0][0]

array([ 0.63898532,  0.46287335,  0.94383511,  0.60858357,  0.63789274,
        0.19030588,  0.41477685,  0.85487615])

dimは、それぞれの特徴量の最大値＋１(値として0が含まれるため)を示す、trainとtestは同じである

In [259]:
trn_dims, tst_dims

([7082, 4, 24, 159], [7082, 4, 24, 159])

In [388]:
dims, rank, reg, regS, lr, lrS, maxEpo

([7082, 4, 24, 159], [8, 8, 8, 8], 0.1, 0.1, 0.0001, 0.0001, 10)

In [391]:
core, U = TPTF(X, Xtest, dims, rank, reg, regS, lr, lrS, maxEpo)

ninstance: 78418, ndims: 4


TypeError: only length-1 arrays can be converted to Python scalars

In [253]:
X[0][36550]

array([6078,    0,   15,   13])